[program:app]
command=uv run flask run --host=127.0.0.1 --port=8050
directory=/app
environment=FLASK_APP="app.py"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
